[bar]
order = [ "Chrisser" ]

    [bar.Chrisser]
    center = [ "workspaces" ]
    end = [ "group:g4", "group:g1", "group:g2" ]
    font_family = "CaskaydiaCove Nerd Font Mono"
    font_weight = 400
    margin_edge = 0
    margin_ends = 0
    radius = 0
    start = [ "group:g3", "media", "audio_visualizer" ]
    widget_spacing = 10

        [[bar.Chrisser.capsule_group]]
        border = "primary"
        fill = "surface_variant"
        foreground = "primary"
        id = "g1"
        members = [ "volume", "battery", "bluetooth" ]
        opacity = 1.0
        padding = 6.0

        [[bar.Chrisser.capsule_group]]
        border = "primary"
        fill = "surface_variant"
        foreground = "tertiary"
        id = "g2"
        members = [ "control-center", "date", "clock", "session" ]
        opacity = 1.0
        padding = 6.0

        [[bar.Chrisser.capsule_group]]
        border = "primary"
        fill = "surface_variant"
        foreground = "secondary"
        id = "g3"
        members = [ "network", "cpu", "ram" ]
        opacity = 1.0
        padding = 10.0

        [[bar.Chrisser.capsule_group]]
        border = "primary"
        fill = "surface_variant"
        foreground = "secondary"
        id = "g4"
        members = [ "notifications", "wallpaper", "mpvpaper", "clipboard" ]
        opacity = 1.0
        padding = 6.0

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-3",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-login-box@DP-4",
    "lockscreen-login-box@HDMI-A-2"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "DP-3"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-4"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1321.0
    output = "DP-4"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-4".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 640.0
    cy = 601.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[plugin_settings."noctalia/mpvpaper"]
video_directory = "/nix/store/9b893sy0sl86gl6lh883kq6zhfgj0cvy-source/assets/backgrounds/animated"

[plugins]
enabled = [ "noctalia/translator", "noctalia/mpvpaper" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    enabled = false
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins/tree/main/mpvpaper"
    name = "liveWallpaper"

[theme]
builtin = "Eldritch"
community_palette = "Monochrome"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "hyprland", "kitty", "qt", "starship" ]
    community_ids = [ "obsidian", "vscode", "rofi", "discord", "steam", "hyprtoolkit" ]
    enable_builtin_templates = true
    enable_community_templates = true

[wallpaper]
directory = "@FLAKE@/assets/backgrounds/berserk"
transition_on_startup = true

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "@FLAKE@/assets/backgrounds/berserk/Armor.jpg"

    [wallpaper.last]
    path = "@FLAKE@/assets/backgrounds/berserk/Armor.jpg"

    [wallpaper.monitors.DP-1]
    path = "/nix/store/ila3vrzilhganjnwk7xp4f4jfilkc3wp-source/assets/backgrounds/berserk/trees.jpg"

    [wallpaper.monitors.DP-3]
    path = "/nix/store/ila3vrzilhganjnwk7xp4f4jfilkc3wp-source/assets/backgrounds/berserk/trees.jpg"

    [wallpaper.monitors.DP-4]
    path = "@FLAKE@/assets/backgrounds/berserk/trees.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "@FLAKE@/assets/backgrounds/berserk/Armor.jpg"

    [wallpaper.monitors.HDMI-A-2]
    path = "@FLAKE@/assets/backgrounds/berserk/trees.jpg"

    [wallpaper.monitors.eDP-1]
    path = "@FLAKE@/assets/backgrounds/berserk/trees.jpg"

[widget.battery]
display_mode = "graphic"

[widget.media]
capsule = true
hide_when_no_media = true
title_scroll = "on_hover"

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.workspaces]
capsule = true
hide_when_empty = true